import os

META_WHATSAPP_VERIFY_TOKEN = os.getenv("META_WHATSAPP_VERIFY_TOKEN", "")
META_WHATSAPP_ACCESS_TOKEN = os.getenv("META_WHATSAPP_ACCESS_TOKEN", "")
META_WHATSAPP_PHONE_NUMBER_ID = os.getenv("META_WHATSAPP_PHONE_NUMBER_ID", "")
META_WHATSAPP_API_VERSION = os.getenv("META_WHATSAPP_API_VERSION", "v21.0")

META_WHATSAPP_BASE_URL = (
    f"https://graph.facebook.com/{META_WHATSAPP_API_VERSION}"
)